# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets executed

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
execDir = os.path.split(thisDir)[1]
dialogBox = RsgDialog(title='Auto CECFDST model', kernelModule='RSG', kernelFunction='parametric_model', includeApplyBtn=False, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=execDir)
RsgHorizontalFrame(name='HFrame_1', p='DialogBox', layout='0', pl=0, pr=0, pt=0, pb=0)
RsgIcon(p='HFrame_1', fileName=r'S.png')
osutils.copy(os.path.join(thisDir,r'S.png'), dialogBox.execDir, force=True)
RsgGroupBox(name='GroupBox_2', p='HFrame_1', text='Geometric dimensions', layout='0')
RsgTextField(p='GroupBox_2', fieldType='Float', ncols=12, labelText='B (Width, mm)                                                ', keyword='B', default='1000')
RsgTextField(p='GroupBox_2', fieldType='Float', ncols=12, labelText='H (Height, mm)                                               ', keyword='H', default='3000')
RsgTextField(p='GroupBox_2', fieldType='Float', ncols=12, labelText='Do (Diameter of outer steel tube, mm)             ', keyword='Do', default='650')
RsgTextField(p='GroupBox_2', fieldType='Float', ncols=12, labelText='Di (Diameter of inner steel tube, mm)               ', keyword='Di', default='272.7')
RsgTextField(p='GroupBox_2', fieldType='Float', ncols=12, labelText='to (Thickness of outer steel tube, mm)              ', keyword='to', default='22')
RsgTextField(p='GroupBox_2', fieldType='Float', ncols=12, labelText='ti (Thickness of inner steel tube, mm)                ', keyword='ti', default='12')
RsgTextField(p='GroupBox_2', fieldType='Float', ncols=12, labelText='dl (Diameter of longitudinal reinforcement, mm)', keyword='dl', default='28.3')
RsgTextField(p='GroupBox_2', fieldType='Float', ncols=12, labelText='dv (Diameter of stirrup, mm)                            ', keyword='dv', default='18')
RsgGroupBox(name='GroupBox_1', p='HFrame_1', text='Material properties', layout='0')
RsgTextField(p='GroupBox_1', fieldType='Float', ncols=12, labelText='fc,o (Cube strength of outer concrete, MPa)               ', keyword='fco', default='50')
RsgTextField(p='GroupBox_1', fieldType='Float', ncols=12, labelText='fc,c (Cube strength of sandwiched concrete, MPa)      ', keyword='fcc', default='60')
RsgTextField(p='GroupBox_1', fieldType='Float', ncols=12, labelText='fy,so (Yield strength of outer steel tube, MPa)            ', keyword='fyso', default='345')
RsgTextField(p='GroupBox_1', fieldType='Float', ncols=12, labelText='fy,si (Yield strength of inner steel tube, MPa)              ', keyword='fysi', default='345')
RsgTextField(p='GroupBox_1', fieldType='Float', ncols=12, labelText='fy,l (Yield strength of longitudinal reinforcement, MPa)', keyword='fyl', default='400')
RsgTextField(p='GroupBox_1', fieldType='String', ncols=12, labelText='fy,v (Yield strength of stirrup, MPa)                            ', keyword='fyv', default='400')
RsgLabel(p='DialogBox', text='Square concrete-encased concrete-filled double-skin steel tube columns', useBoldFont=False)
dialogBox.show()